[package]
name = "ktf-core"
version = "0.1.0"
edition = "2018"
authors = ["CypherLink"]
description = "Keep TDN Forever Plan (Core Library)."
keywords = ["cryptography", "cryptocurrency", "zkp", "tdn"]
categories = ["cryptography", "cryptocurrency"]
license = "MIT/Apache-2.0"

[dependencies]
