[package]
name = "idata-core"
version = "0.1.0"
edition = "2018"
authors = ["Sun"]
description = "iData (Core Library)."
keywords = ["cryptography", "cryptocurrency", "zkp", "data"]
categories = ["cryptography", "cryptocurrency"]
license = "MIT/Apache-2.0"

[dependencies]
